# Generated by Django 5.2.4 on 2025-08-15 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('lessons', '0008_lesson_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lessons.lesson'),
        ),
    ]
