# Generated by Django 5.2.4 on 2025-07-21 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_user_profile'),
        ('profiles', '0002_alter_userprofile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_lessons', to='profiles.userprofile'),
        ),
    ]
