# Generated by Django 5.2.4 on 2025-08-15 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_original_cart_order_stripe_pid'),
        ('lessons', '0007_alter_lesson_description_alter_lesson_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.lesson'),
        ),
    ]
