# Generated by Django 5.2.4 on 2025-07-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacity',
            options={'verbose_name_plural': 'Capacities'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='duration',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date_time']},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={},
        ),
    ]
