# Generated by Django 5.2.4 on 2025-08-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lesson_places_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.CharField(blank=True, choices=[('general.webp', 'general'), ('serve.webp', 'serve'), ('bernardo.webp', 'Bernardo'), ('marina.webp', 'Marina'), ('abel.webp', 'Abel'), ('attack.webp', 'attack')], max_length=255, null=True),
        ),
    ]
