# Generated by Django 5.2.4 on 2025-08-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_lesson_description_alter_lesson_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
